# Generated by Django 5.2.7 on 2025-11-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='artefak',
        ),
        migrations.AddField(
            model_name='report',
            name='artefaks',
            field=models.ManyToManyField(related_name='reports', to='api.artefak'),
        ),
    ]
